sudo: required
services : 
  - docker
before_install : 
  - docker build -t dharag/docker-video-search -f Dockerfile.dev .
script : 
  - docker run -e CI=true dharag/docker-video-search npm run test 
